from minecraft_dashboard.models import FrontendLinkData

ENV_CONFIG_FILE_PATH = "MINECRAFT_DASHBOARD_CONFIG_FILE_PATH"
ENV_HOST = "MINECRAFT_DASHBOARD_HOST"
ENV_PORT = "MINECRAFT_DASHBOARD_PORT"
ENV_LOG_PATH = "MINECRAFT_DASHBOARD_LOG_PATH"
ENV_LOG_LEVEL = "MINECRAFT_DASHBOARD_LOG_LEVEL"
ENV_LOG_FORMAT_FILE = "MINECRAFT_DASHBOARD_LOG_FORMAT_FILE"
ENV_LOG_FORMAT_CONSOLE = "MINECRAFT_DASHBOARD_LOG_FORMAT_CONSOLE"
ENV_LOG_DATE_FORMAT = "MINECRAFT_DASHBOARD_LOG_DATE_FORMAT"
ENV_LOG_FILEMODE = "MINECRAFT_DASHBOARD_LOG_FILEMODE"
ENV_MINECRAFT_SERVER_HOST = "MINECRAFT_DASHBOARD_MINECRAFT_SERVER_HOST"
ENV_MINECRAFT_SERVER_PORT = "MINECRAFT_DASHBOARD_MINECRAFT_SERVER_PORT"
ENV_MINECRAFT_SERVER_HOST_EXTERNAL = (
    "MINECRAFT_DASHBOARD_MINECRAFT_SERVER_HOST_EXTERNAL"
)
ENV_MINECRAFT_SERVER_PORT_EXTERNAL = (
    "MINECRAFT_DASHBOARD_MINECRAFT_SERVER_PORT_EXTERNAL"
)
ENV_MINECRAFT_SERVER_TIMEOUT = "MINECRAFT_DASHBOARD_MINECRAFT_SERVER_TIMEOUT"
ENV_PING_HOST_EXTERNAL = "MINECRAFT_DASHBOARD_PING_HOST_EXTERNAL"
ENV_PING_PORT_EXTERNAL = "MINECRAFT_DASHBOARD_PING_PORT_EXTERNAL"
ENV_FRONTEND_USE_MOCK_DATA = "MINECRAFT_DASHBOARD_FRONTEND_USE_MOCK_DATA"
ENV_FRONTEND_POLLING_INTERVAL = "MINECRAFT_DASHBOARD_FRONTEND_POLLING_INTERVAL"
ENV_FRONTEND_POLLING_INTERVAL_MCSRVSTATUS = (
    "MINECRAFT_DASHBOARD_FRONTEND_POLLING_INTERVAL_MCSRVSTATUS"
)
ENV_FRONTEND_SIMULATE_OFFLINE = "MINECRAFT_DASHBOARD_FRONTEND_SIMULATE_OFFLINE"
ENV_FRONTEND_PAGE_TITLE = "MINECRAFT_DASHBOARD_FRONTEND_PAGE_TITLE"
ENV_FRONTEND_HEADER_TITLE = "MINECRAFT_DASHBOARD_FRONTEND_HEADER_TITLE"
ENV_FRONTEND_LINKS = "MINECRAFT_DASHBOARD_FRONTEND_LINKS"

CONF_CONFIG_FILE_PATH = "config_file_path"
CONF_HOST = "api_host"
CONF_PORT = "api_port"
CONF_LOG_PATH = "log_path"
CONF_LOG_LEVEL = "log_level"
CONF_LOG_FORMAT_FILE = "log_format_file"
CONF_LOG_FORMAT_CONSOLE = "log_format_console"
CONF_LOG_DATE_FORMAT = "log_date_format"
CONF_LOG_FILEMODE = "log_filemode"
CONF_MINECRAFT_SERVER_HOST = "minecraft_server_host"
CONF_MINECRAFT_SERVER_PORT = "minecraft_server_port"
CONF_MINECRAFT_SERVER_HOST_EXTERNAL = "minecraft_server_host_external"
CONF_MINECRAFT_SERVER_PORT_EXTERNAL = "minecraft_server_port_external"
CONF_MINECRAFT_SERVER_TIMEOUT = "minecraft_server_timeout"
CONF_PING_HOST_EXTERNAL = "ping_host_external"
CONF_PING_PORT_EXTERNAL = "ping_port_external"
CONF_FRONTEND_USE_MOCK_DATA = "frontend_use_mock_data"
CONF_FRONTEND_POLLING_INTERVAL = "frontend_polling_interval"
CONF_FRONTEND_POLLING_INTERVAL_MCSRVSTATUS = "frontend_polling_interval_mcsrvstatus"
CONF_FRONTEND_SIMULATE_OFFLINE = "frontend_simulate_offline"
CONF_FRONTEND_PAGE_TITLE = "frontend_page_title"
CONF_FRONTEND_HEADER_TITLE = "frontend_header_title"
CONF_FRONTEND_LINKS = "frontend_links"

DEFAULT_CONFIG_FILE_PATH = "config.yaml"
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 8000
DEFAULT_LOG_PATH = "minecraft_dashboard.log"
DEFAULT_LOG_LEVEL = "info"
DEFAULT_LOG_FORMAT_FILE = "%(asctime)s %(levelname)s %(message)s"
DEFAULT_LOG_FORMAT_CONSOLE = "%(light_black)s%(asctime)s%(reset)s %(log_color)s%(levelname)s%(reset)s %(message)s"
DEFAULT_LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
DEFAULT_LOG_FILEMODE = "a"
DEFAULT_MINECRAFT_SERVER_HOST = "localhost"
DEFAULT_MINECRAFT_SERVER_PORT = 25565
DEFAULT_MINECRAFT_SERVER_HOST_EXTERNAL: str | None = None
DEFAULT_MINECRAFT_SERVER_PORT_EXTERNAL: int | None = None
DEFAULT_MINECRAFT_SERVER_TIMEOUT = 3
DEFAULT_PING_HOST_EXTERNAL = "8.8.8.8"
DEFAULT_PING_PORT_EXTERNAL = 53
DEFAULT_FRONTEND_USE_MOCK_DATA = False
DEFAULT_FRONTEND_POLLING_INTERVAL = 5000
DEFAULT_FRONTEND_POLLING_INTERVAL_MCSRVSTATUS = 60000
DEFAULT_FRONTEND_SIMULATE_OFFLINE = False
DEFAULT_FRONTEND_PAGE_TITLE = "Minecraft Server Dashboard"
DEFAULT_FRONTEND_HEADER_TITLE = "Minecraft Server Dashboard"
DEFAULT_FRONTEND_LINKS: list[FrontendLinkData] = []
